use_frameworks!

target 'SWCircularProgress_Example' do
  pod 'SWCircularProgress', :path => '../'

  target 'SWCircularProgress_Tests' do
    inherit! :search_paths

    pod 'SWCircularProgress', :path => '../'
  end
end
