use_frameworks!

target 'SWCircularProgress_Example' do
  pod 'SWCircularProgress', :path => '../'

  target 'SWCircularProgress_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
